name: Checkstyle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Download Checkstyle
        run: |
          wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.7/checkstyle-10.12.7-all.jar
          mv checkstyle-10.12.7-all.jar checkstyle.jar

      - name: Run Checkstyle
        run: |
          java -jar checkstyle.jar -c .github/workflows/checkstyle.xml src/ || exit 1

      - name: Upload Checkstyle results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-results
          path: checkstyle-result.xml
