name: Checkstyle

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Download Checkstyle
        run: |
          wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.7/checkstyle-10.12.7-all.jar
          mv checkstyle-10.12.7-all.jar checkstyle.jar

      - name: Run Checkstyle
        run: |
          # Create output directory for reports
          mkdir -p reports

          # Run Checkstyle on the jabberpoint package
          java -jar checkstyle.jar -c checkstyle.xml \
            -f xml \
            -o reports/checkstyle-result.xml \
            src/jabberpoint || true

          # Check if any errors were found (optional)
          if grep -q "<error" reports/checkstyle-result.xml; then
            echo "Checkstyle found violations. Check the report for details."
          else
            echo "No Checkstyle violations found."
          fi

      - name: Upload Checkstyle results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: checkstyle-results
          path: reports/checkstyle-result.xml
          retention-days: 14
