name: Code Quality & Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Run Tests
        run: |
          mkdir -p bin
          javac -d bin -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar src/*.java test/*.java
          java -cp bin:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore test.AllTests

      - name: Run Checkstyle
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: "github-pr-review"
          tool_name: "checkstyle"
          checkstyle_config: "checkstyle.xml"
          workdir: src

      - name: Generate JaCoCo Report
        run: |
          # Run tests with JaCoCo
          java -javaagent:lib/jacocoagent.jar -cp bin:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore test.AllTests

          # Generate coverage report
          java -jar lib/jacococli.jar report jacoco.exec \
            --classfiles bin \
            --sourcefiles src \
            --html reports/coverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: reports/coverage
          retention-days: 14
